version: 2
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run: mkdir farhad
      - run: pwd
     # - run: emulator -avd circleci-android22 -no-window
      - run: ls

