version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    
    steps:
      - checkout
      - run: emulator -list-avds
     # - run: emulator -avd circleci-android22 -no-window
      - run: ls

