version: 2
jobs:
  build:
    docker:
     - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir farhad
     # - run: emulator -avd circleci-android22 -no-window
      - run: ls

