version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx1536m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
         name: Start an emulator 
         command: emulator -avd circleci-android22 -no-window:
            background: true
            parallel: true
      - run: echo "A more familiar hi"

