version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    
    steps:
      - checkout
      - run:
         name: Start an emulator 
         command: emulator -avd circleci-android22 -no-window:
            background: true
            parallel: true
      - run: echo "A more familiar hi"

